version: "3"
services: 
  minio: 
    image: minio/minio
    command: server /data
    volumes: 
    - "./data:/data"
    ports: 
    - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
  imageproxy: 
    image: willnorris/imageproxy
    command: -baseURL http://minio:9000/ -addr 0.0.0.0:8080 -cache s3://us-east-1/demo/images?endpoint=minio:9000&disableSSL=1&s3ForcePathStyle=1
    environment:
    - "AWS_ACCESS_KEY_ID=minio"
    - "AWS_SECRET_KEY=minio123"
    ports: 
    - "8080:8080"